global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dynamic-json-targets"
    file_sd_configs:
      - files:
          - "/etc/prometheus/cdp_flink_targets/application_*.json"
        refresh_interval: 5m